export const GET_AQUARIUMS = "GET_AQUARIUMS";
export const ADD_AQUARIUM = "ADD_AQUARIUM";
export const EDIT_AQUARIUM = "EDIT_AQUARIUM";
export const REMOVE_AQUARIUM = "REMOVE_AQUARIUM";
export const ADD_LIVESTOCK = "ADD_LIVESTOCK";
export const ADD_PLANT = "ADD_PLANT";
export const GET_AQUARIUM_BY_ID = "GET_AQUARIUM_BY_ID";
export const REMOVE_LIVESTOCK = "REMOVE_LIVESTOCK";
export const EDIT_LIVESTOCK = "EDIT_LIVESTOCK";
export const ADD_WATERCHANGE = "ADD_WATERCHANGE";

export const ADD_PARAMETERS = "ADD_PARAMETERS";
export const EDIT_PLANT = "EDIT_PLANT";
export const REMOVE_PLANT = "REMOVE_PLANT";

export const START_REQUEST = "START_REQUEST";
export const REQUEST_FAILED = "REQUEST_FAILED";
